---
config:
  themeVariables:
    fontFamily: Monospace
    fontWeight: bold
    edgeLabelBackground: "#0e0e0e"
    # Node border color
    nodeBorder: "#2e2e2e"
  nodeSpacing: 25
  rankSpacing: 25
  flowchart:
    padding: 5
---
graph TD;
  n0["|?&nbsp;&nbsp;|&nbsp;<br>>&nbsp;♥♥&nbsp;|&nbsp;&nbsp;&nbsp;|&nbsp;Cig&nbsp;Saw&nbsp;<br>&nbsp;&nbsp;♥♥&nbsp;|&nbsp;&nbsp;&nbsp;|&nbsp;Adr&nbsp;<br>"]
  style n0 text-align:left,stroke:green;
  d0-7("+3 use Saw<br>shoot")
  n0 --> d0-7
  style d0-7 stroke: green
  linkStyle 0 stroke: green;
  p0-7-0(" live")
  d0-7 --> p0-7-0
  p0-7-0 -->|"33%"| n179
  p0-7-1(" blank")
  d0-7 --> p0-7-1
  p0-7-1 -->|"67%"| n180
  h0("+3 shoot self<br>+3 use Cig shoot self<br>+3 use Cig use Saw shoot<br>+3 use Saw use Cig shoot<br>-7 use Cig shoot<br>-7 use Cig use Saw shoot self<br>-7 use Saw use Cig shoot self<br>-7 use Saw shoot self<br>-9 shoot")
  n0 --> h0
  style h0 text-align:left
  n179["|..|&nbsp;<br>>&nbsp;♥♥&nbsp;|..|&nbsp;Cig&nbsp;<br>X&nbsp;&nbsp;&nbsp;&nbsp;<br>"]
  style n179 text-align:left,stroke:green;
  style n179 fill:#1f9020
  n180["|?&nbsp;|&nbsp;<br>&nbsp;&nbsp;♥♥&nbsp;|&nbsp;&nbsp;|&nbsp;Cig&nbsp;<br>>&nbsp;♥♥&nbsp;|&nbsp;&nbsp;|&nbsp;Adr&nbsp;<br>"]
  style n180 text-align:left,stroke:red;
  d180-0("+6 steal Cig<br>shoot")
  n180 --> d180-0
  style d180-0 stroke: red
  linkStyle 6 stroke: red;
  p180-0-0(" live")
  d180-0 --> p180-0-0
  p180-0-0 -->|"50%"| n181
  p180-0-1(" blank")
  d180-0 --> p180-0-1
  p180-0-1 -->|"50%"| n184
  h180("+3 shoot<br>+0 shoot self<br>0 steal Cig shoot self")
  n180 --> h180
  style h180 text-align:left
  n181["|.|&nbsp;<br>>&nbsp;♥&nbsp;&nbsp;|.|&nbsp;<br>&nbsp;&nbsp;♥♥&nbsp;|.|&nbsp;<br>"]
  style n181 text-align:left,stroke:green;
  d181-0("-6 shoot self")
  n181 --> d181-0
  style d181-0 stroke: green
  linkStyle 12 stroke: green;
  d181-0 --> n182
  h181("-6 shoot")
  n181 --> h181
  style h181 text-align:left
  n182["||&nbsp;<br>>&nbsp;♥&nbsp;&nbsp;<br>&nbsp;&nbsp;♥♥&nbsp;<br>-6,+6"]
  style n182 text-align:left,stroke:green;
  n184["|#|&nbsp;<br>>&nbsp;♥♥&nbsp;|#|&nbsp;<br>&nbsp;&nbsp;♥♥&nbsp;|#|&nbsp;<br>"]
  style n184 text-align:left,stroke:green;
  d184-0("-6 shoot self")
  n184 --> d184-0
  style d184-0 stroke: green
  linkStyle 15 stroke: green;
  d184-0 --> n185
  h184("+6 shoot")
  n184 --> h184
  style h184 text-align:left
  n185["||&nbsp;<br>>&nbsp;♥&nbsp;&nbsp;<br>&nbsp;&nbsp;♥♥&nbsp;<br>-6,+6"]
  style n185 text-align:left,stroke:green;
